# Generated by Django 5.0 on 2023-12-28 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movie_name', models.CharField(max_length=200)),
                ('language', models.CharField(max_length=100)),
                ('movie_type', models.CharField(max_length=100)),
                ('duration', models.IntegerField()),
                ('img', models.ImageField(upload_to='movies')),
            ],
        ),
    ]
