# Generated by Django 5.0 on 2023-12-28 06:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('APP', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='details',
            old_name='movie_type',
            new_name='journer',
        ),
    ]
