# Generated by Django 5.0 on 2023-12-28 07:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('APP', '0002_rename_movie_type_details_journer'),
    ]

    operations = [
        migrations.RenameField(
            model_name='details',
            old_name='journer',
            new_name='genre',
        ),
    ]
