# Generated by Django 5.0 on 2023-12-29 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APP', '0003_rename_journer_details_genre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='details',
            name='duration',
            field=models.FloatField(),
        ),
    ]
