# Generated by Django 5.0 on 2023-12-29 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APP', '0004_alter_details_duration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='details',
            name='duration',
            field=models.CharField(max_length=10),
        ),
    ]
