# Generated by Django 5.0 on 2024-01-02 14:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('APP', '0006_item'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Item',
        ),
    ]
