# Generated by Django 5.0 on 2024-01-03 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APP', '0007_delete_item'),
    ]

    operations = [
        migrations.CreateModel(
            name='Favourites',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movie_name', models.CharField(max_length=200)),
                ('language', models.CharField(max_length=100)),
                ('genre', models.CharField(max_length=100)),
                ('duration', models.CharField(max_length=10)),
                ('img', models.ImageField(upload_to='movies')),
            ],
        ),
    ]
