# Generated by Django 5.0 on 2024-01-03 06:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('APP', '0008_favourites'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='favourites',
            name='img',
        ),
    ]
