# Generated by Django 5.0 on 2024-01-03 07:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APP', '0009_remove_favourites_img'),
    ]

    operations = [
        migrations.CreateModel(
            name='Favourite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movie_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='APP.details')),
            ],
        ),
        migrations.DeleteModel(
            name='Favourites',
        ),
    ]
